# Generated by Django 3.2.6 on 2021-08-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tracking_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
